import { useEffect, useState } from "react";

const translations = {
  en: {
    back: "← Back",
    badge: "Legal",
    title: "Disclaimer",
    intro:
      "Please read this disclaimer carefully before using this website.",
    sections: [
      {
        title: "No Financial Advice",
        text:
          "The content on this website is provided for educational and informational purposes only and does not constitute financial, investment, legal, tax, or professional advice. Users should conduct their own research and consult qualified professionals before making financial decisions.",
      },
      {
        title: "No Guarantee of Accuracy",
        text:
          "While reasonable efforts are made to provide accurate information, no guarantee or warranty is given regarding the accuracy, completeness, reliability, or timeliness of any data, calculations, charts, exchange rates, or results generated by this website.",
      },
      {
        title: "Use at Your Own Risk",
        text:
          "All tools, calculators, projections, simulations, and estimates are provided without warranty of any kind. Use of this website and reliance on its content is entirely at the user's own risk.",
      },
      {
        title: "External Data Sources",
        text:
          "This website may use external APIs and third-party data providers. The operator of this website is not responsible for errors, interruptions, inaccuracies, delays, or missing data originating from third-party services.",
      },
      {
        title: "No Liability",
        text:
          "To the fullest extent permitted under applicable law, the operator of this website shall not be liable for any direct, indirect, incidental, consequential, financial, tax-related, or other damages arising from the use of this website or reliance on its content.",
      },
      {
        title: "No Responsibility for External Links or Affiliates",
        text:
          "This website may contain external links, references, or affiliate services. The operator of this website is not responsible or liable for external websites, services, products, affiliate programs, or third-party content.",
      },
      {
        title: "Jurisdiction",
        text:
          "All legal claims, disputes, or proceedings relating to this website shall be governed exclusively by Swiss law and resolved exclusively in Switzerland.",
      },
      {
        title: "Contact",
        text: "Contact: fintool-kit@proton.me",
      },
    ],
  },

  de: {
    back: "← Zurück",
    badge: "Rechtliches",
    title: "Haftungsausschluss",
    intro:
      "Bitte lies diesen Haftungsausschluss sorgfältig, bevor du diese Website nutzt.",
    sections: [
      {
        title: "Keine Finanzberatung",
        text:
          "Die Inhalte dieser Website dienen ausschliesslich Bildungs- und Informationszwecken und stellen keine Finanz-, Anlage-, Rechts-, Steuer- oder professionelle Beratung dar. Nutzer sollten eigene Recherchen durchführen und qualifizierte Fachpersonen konsultieren.",
      },
      {
        title: "Keine Garantie für Richtigkeit",
        text:
          "Obwohl angemessene Anstrengungen unternommen werden, um korrekte Informationen bereitzustellen, wird keine Garantie hinsichtlich Richtigkeit, Vollständigkeit, Zuverlässigkeit oder Aktualität von Daten, Berechnungen, Diagrammen, Wechselkursen oder Ergebnissen übernommen.",
      },
      {
        title: "Nutzung auf eigenes Risiko",
        text:
          "Alle Tools, Rechner, Projektionen, Simulationen und Schätzungen werden ohne jegliche Gewähr bereitgestellt. Die Nutzung dieser Website erfolgt vollständig auf eigenes Risiko.",
      },
      {
        title: "Externe Datenquellen",
        text:
          "Diese Website kann externe APIs und Drittanbieter-Daten verwenden. Der Betreiber dieser Website übernimmt keine Verantwortung für Fehler, Unterbrechungen, Ungenauigkeiten, Verzögerungen oder fehlende Daten von Drittanbietern.",
      },
      {
        title: "Keine Haftung",
        text:
          "Soweit gesetzlich zulässig, haftet der Betreiber dieser Website nicht für direkte, indirekte, zufällige, finanzielle, steuerliche oder sonstige Schäden, die aus der Nutzung dieser Website entstehen.",
      },
      {
        title: "Keine Verantwortung für externe Links oder Affiliates",
        text:
          "Diese Website kann externe Links, Verweise oder Affiliate-Dienste enthalten. Der Betreiber übernimmt keine Verantwortung oder Haftung für externe Websites, Dienstleistungen, Produkte, Affiliate-Programme oder Inhalte Dritter.",
      },
      {
        title: "Gerichtsstand",
        text:
          "Alle rechtlichen Ansprüche oder Streitigkeiten im Zusammenhang mit dieser Website unterliegen ausschliesslich schweizerischem Recht und werden ausschliesslich in der Schweiz entschieden.",
      },
      {
        title: "Kontakt",
        text: "Kontakt: fintool-kit@proton.me",
      },
    ],
  },

  fr: {
    back: "← Retour",
    badge: "Mentions légales",
    title: "Avertissement",
    intro:
      "Veuillez lire attentivement cet avertissement avant d’utiliser ce site.",
    sections: [
      {
        title: "Aucun conseil financier",
        text:
          "Le contenu de ce site est fourni uniquement à des fins éducatives et informatives et ne constitue pas un conseil financier, juridique, fiscal ou professionnel.",
      },
      {
        title: "Aucune garantie d’exactitude",
        text:
          "Aucune garantie n’est donnée concernant l’exactitude, l’exhaustivité ou la fiabilité des données, calculs, graphiques, taux de change ou résultats générés par ce site.",
      },
      {
        title: "Utilisation à vos risques",
        text:
          "Tous les outils, calculateurs et simulations sont fournis sans garantie. L’utilisation du site se fait entièrement aux risques de l’utilisateur.",
      },
      {
        title: "Sources de données externes",
        text:
          "Ce site peut utiliser des API et fournisseurs de données tiers. L’exploitant n’est pas responsable des erreurs ou interruptions provenant de ces services.",
      },
      {
        title: "Limitation de responsabilité",
        text:
          "Dans les limites autorisées par la loi, l’exploitant ne pourra être tenu responsable des dommages résultant de l’utilisation du site.",
      },
      {
        title: "Liens externes et affiliés",
        text:
          "Ce site peut contenir des liens externes ou des services affiliés. L’exploitant n’est pas responsable des contenus, produits ou services tiers.",
      },
      {
        title: "Juridiction",
        text:
          "Tous les litiges liés à ce site sont soumis exclusivement au droit suisse et aux tribunaux suisses.",
      },
      {
        title: "Contact",
        text: "Contact : fintool-kit@proton.me",
      },
    ],
  },
};

export default function DisclaimerPage() {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const browserLang = navigator.language.toLowerCase();

    if (browserLang.startsWith("de")) {
      setLang("de");
    } else if (browserLang.startsWith("fr")) {
      setLang("fr");
    } else {
      setLang("en");
    }
  }, []);

  const t = translations[lang] || translations.en;

  return (
    <main style={styles.page}>
      <div style={styles.card}>
        <a href="/" style={styles.backLink}>
          {t.back}
        </a>

        <div style={styles.badge}>{t.badge}</div>

        <h1 style={styles.title}>{t.title}</h1>

        <p style={styles.intro}>{t.intro}</p>

        <div style={styles.sections}>
          {t.sections.map((section, index) => (
            <section key={index} style={styles.section}>
              <h2 style={styles.sectionTitle}>{section.title}</h2>
              <p style={styles.sectionText}>{section.text}</p>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}

const styles = {
  page: {
    minHeight: "100vh",
    margin: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background:
      "linear-gradient(135deg, #fee2e2 0%, #f8fafc 45%, #fecaca 100%)",
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif",
    padding: "20px",
  },

  card: {
    width: "100%",
    maxWidth: "920px",
    background: "rgba(255,255,255,0.95)",
    padding: "38px",
    borderRadius: "28px",
    boxShadow: "0 24px 70px rgba(15,23,42,0.14)",
    border: "1px solid rgba(255,255,255,0.8)",
  },

  backLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    marginBottom: "28px",
    padding: "8px 14px",
    borderRadius: "999px",
    background: "#fef2f2",
    color: "#dc2626",
    textDecoration: "none",
    fontWeight: "700",
    fontSize: "14px",
  },

  badge: {
    display: "inline-block",
    padding: "6px 12px",
    borderRadius: "999px",
    background: "#fee2e2",
    color: "#b91c1c",
    fontSize: "13px",
    fontWeight: "700",
    marginBottom: "16px",
  },

  title: {
    margin: 0,
    fontSize: "38px",
    letterSpacing: "-0.04em",
    color: "#0f172a",
  },

  intro: {
    marginTop: "12px",
    marginBottom: "32px",
    color: "#64748b",
    fontSize: "16px",
    lineHeight: 1.7,
  },

  sections: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },

  section: {
    padding: "22px",
    borderRadius: "18px",
    background: "#fff",
    border: "1px solid #e2e8f0",
  },

  sectionTitle: {
    margin: "0 0 10px",
    fontSize: "22px",
    color: "#0f172a",
    letterSpacing: "-0.03em",
  },

  sectionText: {
    margin: 0,
    color: "#334155",
    fontSize: "15px",
    lineHeight: 1.8,
  },
};
